name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest test_calculator.py
        continue-on-error: true
        id: unit_test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build package
        run: |
          mkdir build
          cp calculator.py build/
          echo "Build completed" > build/build.log

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/

  notify:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Install mailutils
        run: |
          sudo apt-get update
          sudo apt-get install -y mailutils

      - name: Set email environment variable
        run: echo "EMAIL_RECIPIENT=${{ secrets.EMAIL_RECIPIENT }}" >> $GITHUB_ENV

      - name: Send notification email
        run: |
          if [[ "${{ needs.test.outputs.exitcode }}" == "0" ]]; then
            echo "success" > status.txt
          else
            echo "failure" > status.txt
          fi
          STATUS=$(cat status.txt)
          bash send_email.sh "$EMAIL_RECIPIENT" "$STATUS"
